#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /etc/tor/torrc.anon
    if [ -e /etc/tor/torrc.orig ]; then
        mv /etc/tor/torrc.orig /etc/tor/torrc
    fi
fi
if [ "$1" = "purge" ]; then
    rm -rf /etc/anonsurf
fi
